version: '2'
plugins:
  test_reporter:
    enabled: true
    language: node_js
node_js:
  - "node"
script:
  - npm test
after_script:
  - npm run coverage
  - CODECLIMATE_REPO_TOKEN=770c18eeee19024948ed82bdb97e6de5aaac02014aae3f601631a0dfbdb66600 ./node_modules/.bin/codeclimate-test-reporter coverage/lcov.info